/**
 * Official or primary product URLs for guide tool pills.
 * Keys MUST match labels in guideToolsData.js.
 */
export const TOOL_WEBSITE_BY_LABEL = Object.freeze({
  "3ds Max": "https://www.autodesk.com/products/3ds-max/overview",
  "Adobe After Effects": "https://www.adobe.com/products/aftereffects.html",
  "Adobe Color": "https://color.adobe.com/",
  "Adobe Dimension": "https://www.adobe.com/products/dimension.html",
  "Adobe Express": "https://www.adobe.com/express/",
  "Adobe Firefly": "https://www.adobe.com/products/firefly.html",
  "Adobe Illustrator": "https://www.adobe.com/products/illustrator.html",
  "Adobe InDesign": "https://www.adobe.com/products/indesign.html",
  "Adobe Lightroom": "https://www.adobe.com/products/photoshop-lightroom.html",
  "Adobe Photoshop": "https://www.adobe.com/products/photoshop.html",
  "Adobe Premiere Pro": "https://www.adobe.com/products/premiere.html",
  "Adobe Substance 3D": "https://www.adobe.com/products/substance3d.html",
  "Adobe XD": "https://www.adobe.com/products/xd.html",
  "Affinity Designer": "https://affinity.serif.com/en/designer/",
  "Affinity Photo": "https://affinity.serif.com/en/photo/",
  "Affinity Publisher": "https://affinity.serif.com/en/publisher/",
  "Airtable": "https://airtable.com/",
  "Apple Keynote": "https://www.apple.com/keynote/",
  "ArtiosCAD": "https://www.esko.com/en/products/cad_suite/artioscad",
  "Asana": "https://asana.com/",
  "Attention Insight": "https://attentioninsight.com/",
  "AutoCAD": "https://www.autodesk.com/products/autocad/overview",
  "Autodesk Maya": "https://www.autodesk.com/products/maya/overview",
  "Axe DevTools": "https://www.deque.com/axe/devtools/",
  "Axure RP": "https://www.axure.com/",
  "Backlight": "https://backlight.dev/",
  "Balsamiq": "https://balsamiq.com/",
  "Baseline": "https://baseline.is/",
  "Bevy": "https://bevyengine.org/",
  "Bezi": "https://www.bezi.app/",
  "Bezi (ShapesXR)": "https://www.bezi.app/",
  "Birdfont": "https://birdfont.org/",
  "Blender": "https://www.blender.org/",
  "Boxshot": "https://www.boxshot.com/",
  "Brandmark": "https://www.brandmark.io/",
  "Bravo Studio": "https://www.bravostudio.app/",
  "Campfire": "https://www.campfire3d.com/",
  "Canva": "https://www.canva.com/",
  "CapCut": "https://www.capcut.com/",
  "Capture One": "https://www.captureone.com/",
  "Cascadeur": "https://cascadeur.com/",
  "Cavalry": "https://cavalry.scenegroup.co/",
  "Chamaileon": "https://chamaileon.io/",
  "Chart.js": "https://www.chartjs.org/",
  "Cinema 4D": "https://www.maxon.net/en/cinema-4d",
  "Clarity": "https://clarity.microsoft.com/",
  "Claude": "https://claude.ai/",
  "Clip Studio Paint": "https://www.clipstudio.net/en",
  "Color Oracle": "https://colororacle.org/",
  "ColorBox": "https://www.color-box.io/",
  "Condens": "https://condens.io/",
  "Coolors": "https://coolors.co/",
  "Corel Painter": "https://www.painterartist.com/",
  "CorelDRAW": "https://www.coreldraw.com/",
  "Crazy Egg": "https://www.crazyegg.com/",
  "CrazyEgg": "https://www.crazyegg.com/",
  "Creatie": "https://creatie.design/",
  "Creative Edge iC3D": "https://creativeedgesoftware.com/ic3d",
  "Cursor": "https://cursor.com/",
  "D3.js": "https://d3js.org/",
  "DaVinci Resolve": "https://www.blackmagicdesign.com/products/davinciresolve",
  "Defold": "https://defold.com/",
  "Descript": "https://www.descript.com/",
  "Dora": "https://www.dora.run/",
  "Dovetail": "https://dovetail.com/",
  "Dyspatch": "https://www.dyspatch.io/",
  "Esko Studio": "https://www.esko.com/",
  "Evinced": "https://evinced.com/",
  "Evoto": "https://evoto.ai/",
  "Fable": "https://www.fablesquare.com/",
  "FigJam": "https://www.figma.com/figjam/",
  "Figma": "https://www.figma.com/",
  "Final Cut Pro": "https://www.apple.com/final-cut-pro/",
  "FlexiSign": "https://www.thinksai.com/software/flexi/",
  "Flourish": "https://flourish.studio/",
  "FlowMapp": "https://flowmapp.com/",
  "Foleon": "https://www.foleon.com/",
  "FontLab": "https://www.fontlab.com/",
  "Fontra": "https://github.com/googlefonts/fontra",
  "Framer": "https://www.framer.com/",
  "Frontify": "https://www.frontify.com/",
  "Galileo AI": "https://www.usegalileo.ai/",
  "Gamma": "https://gamma.app/",
  "Glorify": "https://glorify.com/",
  "Glyphs": "https://glyphsapp.com/",
  "Godot": "https://godotengine.org/",
  "Google Analytics (GA4)": "https://marketingplatform.google.com/about/analytics/",
  "Google Search Console (GSC)": "https://search.google.com/search-console/about",
  "Google Slides": "https://www.google.com/slides/about/",
  "Google Tag Manager (GTM)": "https://marketingplatform.google.com/about/tag-manager/",
  "Hero Forge": "https://www.heroforge.com/",
  "Highcharts": "https://www.highcharts.com/",
  "Hotjar": "https://www.hotjar.com/",
  "Huemint": "https://huemint.com/",
  "iA Presenter": "https://ia.net/presenter",
  "IconJar": "https://www.geticonjar.com/",
  "Jira": "https://www.atlassian.com/software/jira",
  "Jitter": "https://jitter.video/",
  "Judo": "https://developer.judo.app/",
  "Keynote": "https://www.apple.com/keynote/",
  "Kittl": "https://www.kittl.com/",
  "Krea AI": "https://www.krea.ai/",
  "Krita": "https://krita.org/",
  "Lens Studio": "https://ar.snap.com/lens-studio",
  "Leonardo": "https://leonardo.ai/",
  "Leonardo AI": "https://leonardo.ai/",
  "Linear": "https://linear.app/",
  "Linearity Curve (Vectornator)": "https://www.linearity.io/curve/",
  "Linearity Move": "https://www.linearity.io/move/",
  "Lingo": "https://www.lingoapp.com/",
  "Litmus": "https://www.litmus.com/",
  "Lookback": "https://lookback.io/",
  "LottieFiles": "https://lottiefiles.com/",
  "LottieLab": "https://www.lottie.com/products/lottie-lab",
  "Lucidchart": "https://www.lucidchart.com/",
  "Lyssna": "https://www.lyssna.com/",
  "Magician": "https://www.figma.com/community/file/1184069065763242572",
  "Maglr": "https://www.maglr.com/",
  "Magma": "https://magma.com/",
  "Magnific AI": "https://magnific.ai/",
  "Mailchimp": "https://mailchimp.com/",
  "Maze": "https://maze.co/",
  "Microsoft Clarity": "https://clarity.microsoft.com/",
  "Microsoft Designer": "https://designer.microsoft.com/",
  "Microsoft PowerPoint": "https://www.microsoft.com/microsoft-365/powerpoint",
  "Midjourney": "https://www.midjourney.com/",
  "Milanote": "https://milanote.com/",
  "Mind the Graph": "https://mindthegraph.com/",
  "Miro": "https://miro.com/",
  "Mitosis": "https://mitosis.builder.io/",
  "Moho (Anime Studio)": "https://moho.lostmarble.com/",
  "Mural": "https://www.mural.co/",
  "Notion": "https://www.notion.so/",
  "Nucleo": "https://nucleoapp.com/",
  "Observable": "https://observablehq.com/",
  "Octopus.do": "https://octopus.do/",
  "Optimal Workshop": "https://www.optimalworkshop.com/",
  "Optimizely": "https://www.optimizely.com/",
  "Opus Clip": "https://www.opus.pro/",
  "Pacdora": "https://www.pacdora.com/",
  "Penpot": "https://penpot.app/",
  "Photoroom": "https://www.photoroom.com/",
  "Piktochart": "https://piktochart.com/",
  "Pitch": "https://pitch.com/",
  "Plasticity": "https://www.plasticity.xyz/",
  "Play": "https://www.createwithplay.com/",
  "PlayCanvas": "https://playcanvas.com/",
  "Polycam": "https://poly.cam/",
  "PostHog": "https://posthog.com/",
  "Power BI": "https://powerbi.microsoft.com/",
  "Principle": "https://principleformac.com/",
  "Procreate": "https://procreate.com/",
  "ProtoPie": "https://www.protopie.io/",
  "QuarkXPress": "https://www.quark.com/products/quarkxpress",
  "Radiant Photo": "https://radiantimaginglabs.com/",
  "RawGraphs": "https://www.rawgraphs.io/",
  "React / Vue (Frameworks)": "https://react.dev/",
  "Readymag": "https://readymag.com/",
  "Recharts": "https://recharts.org/",
  "Recraft": "https://www.recraft.ai/",
  "Relume": "https://www.relume.io/",
  "Rive": "https://rive.app/",
  "RoboFont": "https://robofont.com/",
  "RunwayAI": "https://runwayml.com/",
  "ShapesXR": "https://www.shapesxr.com/",
  "Sketch": "https://www.sketch.com/",
  "SketchUp": "https://www.sketchup.com/",
  "Spark AR": "https://spark.meta.com/spark-studio",
  "Specify": "https://specifyapp.com/",
  "Spline": "https://spline.design/",
  "Sprig": "https://sprig.com/",
  "Stark": "https://www.getstark.co/",
  "Storybook": "https://storybook.js.org/",
  "Stratpad": "https://www.stratpad.com/",
  "Stripo": "https://stripo.email/",
  "Studio.design": "https://studio.design/",
  "Supernova": "https://supernova.io/",
  "Tableau": "https://www.tableau.com/",
  "Tokens Studio": "https://tokens.studio/",
  "Tome": "https://tome.app/",
  "Toon Boom Harmony": "https://www.toonboom.com/",
  "Tremor": "https://tremor.so/",
  "Twine": "https://twinery.org/",
  "Typeform": "https://www.typeform.com/",
  "Uizard": "https://uizard.io/",
  "Unity": "https://unity.com/",
  "Unreal Engine": "https://www.unrealengine.com/",
  "Useberry": "https://www.useberry.com/",
  "UserTesting": "https://www.usertesting.com/",
  "UXPin": "https://www.uxpin.com/",
  "UXPin Merge": "https://www.uxpin.com/merge/",
  "v0": "https://v0.dev/",
  "VectorStyler": "https://vectorstyler.com/",
  "Vectorworks": "https://www.vectorworks.net/",
  "Vev": "https://www.vev.design/",
  "Visily": "https://www.visily.ai/",
  "VistaCreate": "https://create.vista.com/",
  "VisualEyes": "https://www.visually.ai/en/product/visualeyes",
  "Vizcom": "https://vizcom.ai/",
  "VRoid Studio": "https://vroid.com/en/studio/",
  "VWO": "https://vwo.com/",
  "WAVE": "https://wave.webaim.org/",
  "Webflow": "https://webflow.com/",
  "Womp": "https://www.womp.com/",
  "ZBrush": "https://www.maxon.net/en/zbrush",
  "ZeBrand": "https://brand.ze-brand.com/login",
  "Zeplin": "https://zeplin.io/",
  "Zeroheight": "https://zeroheight.com/",
});

/**
 * Resolve a sanitized https URL for a tool label, or null when unknown.
 * @param {unknown} label
 * @returns {string | null}
 */
export function resolveToolWebsiteUrl(label) {
  const k = typeof label === "string" ? label.trim() : "";
  if (!k) return null;
  const raw = TOOL_WEBSITE_BY_LABEL[k];
  if (typeof raw !== "string") return null;
  try {
    const u = new URL(raw.trim());
    if (u.protocol !== "https:") return null;
    return u.href;
  } catch {
    return null;
  }
}
